---
- name: Use short module names
  hosts: all
  tasks:
    - ansible.builtin.copy:
        src: /etc/hosts
        dest: /tmp/hosts
    - ansible.builtin.template: src=foo.j2 dest=/tmp/foo
    - ansible.builtin.file:
        path: /tmp/bar
        state: touch
    - ansible.builtin.service: name=sshd state=restarted
    - ansible.builtin.shell: echo hello
    - ansible.builtin.command: /bin/true
    - ansible.builtin.apt:
        name: vim
        state: present
    - ansible.builtin.get_url:
        url: https://example.com/file
        dest: /tmp/file

# Below should not accidentally convert values that are already FQCN or comments
- name: Already FQCN
  tasks:
    - name: copy task
      ansible.builtin.copy:
        src: a
        dest: b
    - ansible.builtin.debug: msg="copy: test"  # string containing 'copy:'
    - ansible.builtin.git:
        repo: https://example.com/repo.git
        dest: /srv/repo
        user: deploy  # should remain a param, not fqcn
